### ISSUE TITLE
svgs are invisible when using darkmode on github

### ISSUE THREAD

**Issue by MichaelDimmitt** [areebbeigh/areebbeigh#1]
![what your profile looks like](https://user-images.githubusercontent.com/11463275/103157680-83a74f00-4783-11eb-8c21-77208c19e85b.png)

consider switching the color away from black 👍
maybe gray or blue

**Comment by areebbeigh** [comment]
Hey, thanks! Will do.

**Comment by areebbeigh** [comment]
Fixed! ✌🏼
